# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-31 03:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0002_auto_20180331_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingentry',
            name='billing_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 3, 20, 45, 871959)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 3, 20, 45, 873977)),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 3, 20, 45, 866353)),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='auth_token',
            field=models.CharField(default=b'daafd6e3-091d-4b75-b14b-0816d58bcd92', max_length=512),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 3, 20, 45, 869343)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 3, 20, 45, 875367)),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='track_status',
            field=models.CharField(choices=[(b'Initiated', b'Initiated'), (b'Pending', b'Pending'), (b'Accepted', b'Accepted'), (b'Rejected', b'Rejected')], default=b'Initiated', max_length=124),
        ),
    ]
